
const TVLS = [
    {
        id: "bake", 
        name: "化物语", 
        jp: "bakemonogatari", 
        time: "2009-07", 
        post: "https://img.cycimg.me/pic/cover/l/64/7c/1671_vQ2W9.jpg"
    }, {
        id: "nise", 
        name: "偽物語", 
        jp: "nisemonogatari", 
        time: "2012-01", 
        post: "https://img.cycimg.me/pic/cover/l/8e/28/23161_y2AEb.jpg"
    }, {
        id: "nekokuro", 
        name: "猫物語(黑)", 
        jp: "nekomonogatari(kuro)", 
        time: "2012-01", 
        post: "https://img.cycimg.me/pic/cover/l/f1/d6/56117_o7a7a.jpg"
    }, {
        id: "nekoshiro", 
        name: "猫物語(白)", 
        jp: "nekomonogatari(shiro)", 
        time: "2013-07", 
        post: "https://tx-free-imgs.acfun.cn/oyKU6Wes2M-aEJFB3-YNBRvm-Ejmaui-niENZf.png"
    }, {
        id: "kabu", 
        name: "傾物語", 
        jp: "kabukimonogatari", 
        time: "2013-07", 
        post: "https://tx-free-imgs.acfun.cn/UyyOrw7JJD-EneaIb-qeuima-Y7zANb-Ivauai.png"
    }, {
        id: "otori", 
        name: "囮物語", 
        jp: " otorimonogatari", 
        time: "2013-07", 
        post: "https://tx-free-imgs.acfun.cn/JUBMxI9MIJ-MRR7bm-7vua6n-RNNRJf-jUfQvm.png"
    }, {
        id: "oni", 
        name: "鬼物語", 
        jp: "onimonogatari", 
        time: "2013-07", 
        post: "https://tx-free-imgs.acfun.cn/LGmqP7I1XT-i22y6f-aeemma-yYN3Mj-qMNrEj.png"
    }, {
        id: "koi", 
        name: "恋物語", 
        jp: "koimonogatari", 
        time: "2013-07", 
        post: "https://tx-free-imgs.acfun.cn/HguSpnwR0P-nqeeIj-qyMVji-MriuQz-YnMfqe.png"
    }, {
        id: "hana", 
        name: "花物語", 
        jp: "hanamonogatari", 
        time: "2014-08", 
        post: "https://tx-free-imgs.acfun.cn/8rfaW5lCwW-InYFzi-22QZ7j-fAJbUv-3EBFJz.png"
    }, {
        id: "tsuki", 
        name: "憑物語", 
        jp: "tsukimonogatari", 
        time: "2014-12", 
        post: "https://tx-free-imgs.acfun.cn/X37mGkfW5X-zea2Ij-IVZvQn-Uzye6b-RZjqAn.png"
    }, {
        id: "owari", 
        name: "終物語", 
        jp: "owarimonogatari", 
        time: "2015-10", 
        post: "https://img.cycimg.me/pic/cover/l/b0/4d/138829_QtBqr.jpg"
    }, {
        id: "kizu", 
        name: "傷物語", 
        jp: "kizumonogatari", 
        time: "2016-01", 
        post: "https://img.cycimg.me/pic/cover/l/bf/9c/7707_4370B.jpg"
    }, {
        id: "koyomi", 
        name: "暦物語", 
        jp: "koyomimonogatari", 
        time: "2016-01", 
        post: "https://img.cycimg.me/pic/cover/l/23/f8/146104_lFg3g.jpg"
    }, {
        id: "owarige", 
        name: "終物語・下", 
        jp: "owarimonogatari", 
        time: "2016-01", 
        post: "https://img.cycimg.me/pic/cover/l/53/29/175596_3cC5H.jpg"
    }, {
        id: "zoku", 
        name: "続・終物語", 
        jp: "zoku-owarimonogatari", 
        time: "2016-01", 
        post: "https://img.cycimg.me/pic/cover/l/3a/7f/233926_V09ek.jpg"
    }, 
];
